import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="border-b border-neutral-200">
          <div className="mx-auto flex w-full max-w-3xl items-center justify-between px-6 py-4">
            <Link href="/" className="text-sm font-semibold tracking-tight text-neutral-900">
              Axiom
            </Link>
            <nav className="flex items-center gap-4 text-sm">
              <Link
                href="/resources"
                className="text-neutral-700 underline-offset-4 hover:underline"
              >
                Resources
              </Link>
            </nav>
          </div>
        </header>

        {children}

        <footer className="mt-16 border-t border-neutral-200">
          <div className="mx-auto w-full max-w-3xl px-6 py-8 text-sm text-neutral-600">
            <p className="mb-2">Axiom — daily logic, clean thinking.</p>
            <p>
              <Link className="text-neutral-800 underline-offset-4 hover:underline" href="/resources">
                Resources
              </Link>
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
